AWSTemplateFormatVersion: '2010-09-09'
Description: Portfolio setup for Service Catalog with EC2 and VPC products. (fdp-1p4da46nc)
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network parameters
        Parameters:
          - VPCCIDR
          - PrivateSubnet2ACIDR
          - PrivateSubnet2BCIDR
          - PublicSubnet2ACIDR
          - PublicSubnet2BCIDR
          - AvailabilityZone1
          - AvailabilityZone2

Parameters:
  VPCCIDR:
    Type: String
    Default: '192.29.10.0/24'
  PrivateSubnet2ACIDR:
    Type: String
    Default: '192.29.10.0/26'
    Description: CIDR block for private subnet 2A
  PrivateSubnet2BCIDR:
    Type: String
    Default: '192.29.10.64/26'
    Description: CIDR block for private subnet 2B
  PublicSubnet2ACIDR:
    Type: String
    Default: '192.29.10.128/26'
    Description: CIDR block for public subnet 2A
  PublicSubnet2BCIDR:
    Type: String
    Default: '192.29.10.192/26'
    Description: CIDR block for public subnet 2B
  AvailabilityZone1:
    Type: String
    Description: The first Availability Zone to use for the subnets
    Default: "us-east-1a"
  AvailabilityZone2:
    Type: String
    Description: The second Availability Zone to use for the subnets
    Default: "us-east-1b"

Resources:
  #blumbing first
  DHCPOptions:
    Type: AWS::EC2::DHCPOptions
    Properties:
      DomainName: 'ec2.internal'
      DomainNameServers:
        - AmazonProvidedDNS

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: 'Network Lab VPC'

  VPCDHCPOptionsAssociation:
    Type: AWS::EC2::VPCDHCPOptionsAssociation
    Properties:
      VpcId: !Ref VPC
      DhcpOptionsId: !Ref DHCPOptions

  PrivateSubnet2A:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnet2ACIDR
      AvailabilityZone: !Ref AvailabilityZone1
      Tags:
        - Key: Name
          Value: 'Private subnet 2A'
        - Key: Network
          Value: Private

  PrivateSubnet2B:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnet2BCIDR
      AvailabilityZone: !Ref AvailabilityZone2
      Tags:
        - Key: Name
          Value: 'Private subnet 2B'
        - Key: Network
          Value: Private

  PrivateSubnetRouteTableA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: 'Private subnets A'
        - Key: Network
          Value: Private

  PublicSubnet2A:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnet2ACIDR
      AvailabilityZone: !Ref AvailabilityZone1
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: 'Public subnet 2A'
        - Key: Network
          Value: Public

  PublicSubnet2B:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnet2BCIDR
      AvailabilityZone: !Ref AvailabilityZone2
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: 'Public subnet 2B'
        - Key: Network
          Value: Public

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Network
          Value: Public

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnetRouteTableA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: 'Public subnets 2a'
        - Key: Network
          Value: Public

  PublicSubnetRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicSubnetRouteTableA
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet2ARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2A
      RouteTableId: !Ref PublicSubnetRouteTableA

  PublicSubnet2BRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2B
      RouteTableId: !Ref PublicSubnetRouteTableA

  PrivateSubnet2ARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2A
      RouteTableId: !Ref PrivateSubnetRouteTableA

  PrivateSubnet2BRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2B
      RouteTableId: !Ref PrivateSubnetRouteTableA

  # Endpoints
  CfnEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPC
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.cloudformation"
      VpcEndpointType: "Interface"
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref PrivateSubnet2A
      SecurityGroupIds:
        - !Ref EndpointSG

  S3VPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPC
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: '*'
            Effect: Allow
            Resource: '*'
            Principal: '*'
      RouteTableIds:
        - !Ref PrivateSubnetRouteTableA
        - !Ref PublicSubnetRouteTableA
      ServiceName: !Join ['', ['com.amazonaws.', !Ref 'AWS::Region', '.s3']]
      VpcId: !Ref VPC

  STSEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPC
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.sts"
      VpcEndpointType: "Interface"
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref PrivateSubnet2A
      SecurityGroupIds:
        - !Ref EndpointSG

  EndpointSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Traffic into CloudFormation Endpoint"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: "192.29.10.0/24"
        - IpProtocol: udp
          FromPort: 53
          ToPort: 53
          CidrIp: "192.29.10.0/24"
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: EndpointSG

Outputs:
  VPCID:
    Description: VPC ID
    Value: !Ref VPC
    Export:
      Name: 'Network-VPC-A'
  PrivateSubnet2A:
    Description: Private subnet 2A
    Value: !Ref PrivateSubnet2A
    Export:
      Name: 'Network-PrivateSubnet2A'
  PrivateSubnet2ACIDR:
    Description: Private subnet 2A CIDR
    Value: !Ref PrivateSubnet2ACIDR
    Export:
      Name: 'Network-PrivateSubnet2ACIDR'
  PrivateSubnet2B:
    Description: Private subnet 2B
    Value: !Ref PrivateSubnet2B
    Export:
      Name: 'Network-PrivateSubnet2B'
  PrivateSubnet2BCIDR:
    Description: Private subnet 2B CIDR
    Value: !Ref PrivateSubnet2BCIDR
    Export:
      Name: 'Network-PrivateSubnet2BCIDR'
  PrivateSubnetRouteTableA:
    Description: Subnet Route Table
    Value: !Ref PrivateSubnetRouteTableA
    Export:
      Name: Network-PrivateSubnetRouteTableA
  PublicSubnet2A:
    Description: Public subnet 2A
    Value: !Ref PublicSubnet2A
    Export:
      Name: 'Network-PublicSubnet2A'
  PublicSubnet2ACIDR:
    Description: Public subnet 2A CIDR
    Value: !Ref PublicSubnet2ACIDR
    Export:
      Name: 'Network-2-PublicSubnet2ACIDR'
  PublicSubnet2B:
    Description: Public subnet 2B
    Value: !Ref PublicSubnet2B
    Export:
      Name: 'Network-PublicSubnet2B'
  PublicSubnet2BCIDR:
    Description: Public subnet 2B CIDR
    Value: !Ref PublicSubnet2BCIDR
    Export:
      Name: 'Network-2-PublicSubnet2BCIDR'